# Generated by Django 5.2.18 on 2026-10-09 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_enrollment_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=3000, verbose_name="سوال")),
                ("answer", models.TextField(blank=True, verbose_name="پاسخ")),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پاسخ"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="سوال نامناسب یا تکراری برای دانشجوها نمایش داده نشود",
                        verbose_name="مخفی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان سوال"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalog.lesson",
                        verbose_name="جلسه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پرسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوال\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
