# Generated by Django 5.2.18 on 2026-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="کاربر تا رمز خود را عوض نکند به بخش\u200cهای دیگر دسترسی ندارد.",
                verbose_name="الزام به تغییر رمز",
            ),
        ),
    ]
