# Generated by Django 5.2.18 on 2026-10-09 10:36

import apps.videos.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=apps.videos.models.source_upload_to,
                        verbose_name="فایل اصلی",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نام فایل"
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(default=0, verbose_name="حجم فایل اصلی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در صف تبدیل"),
                            ("processing", "در حال تبدیل"),
                            ("ready", "آماده پخش"),
                            ("failed", "خطا"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت (ثانیه)"
                    ),
                ),
                (
                    "renditions",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کیفیت\u200cها"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="خطا")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="آپلود"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="catalog.lesson",
                        verbose_name="جلسه",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدیو",
                "verbose_name_plural": "ویدیوها",
            },
        ),
    ]
