# Generated by Django 5.2.18 on 2026-10-09 11:10

import apps.catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=300, verbose_name="خلاصه"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.catalog.models.cover_upload_to,
                        verbose_name="تصویر جلد",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی = نامحدود",
                        null=True,
                        verbose_name="ظرفیت",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منتشر شده"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
            ],
            options={
                "verbose_name": "کلاس زنده",
                "verbose_name_plural": "کلاس\u200cهای زنده",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان جلسه")),
                ("starts_at", models.DateTimeField(verbose_name="زمان شروع")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=90, verbose_name="مدت (دقیقه)"),
                ),
                (
                    "meet_link",
                    models.URLField(blank=True, verbose_name="لینک Google Meet"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "reminder_day_sent_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "reminder_hour_sent_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "live_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="live.liveclass",
                        verbose_name="کلاس",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه زنده",
                "verbose_name_plural": "جلسه\u200cهای زنده",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="یادداشت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ثبت\u200cنام"
                    ),
                ),
                (
                    "live_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="live.liveclass",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_registrations",
                        to="shop.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت\u200cنام کلاس زنده",
                "verbose_name_plural": "ثبت\u200cنام\u200cهای کلاس زنده",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "live_class"), name="one_registration_per_user"
                    )
                ],
            },
        ),
    ]
