# Generated by Django 5.2.18 on 2026-10-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="آموزش هوش مصنوعی مکانی",
                        max_length=100,
                        verbose_name="نام سایت",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="دوره\u200cهای تخصصی GeoAI، سنجش از دور و تحلیل داده\u200cهای مکانی",
                        max_length=200,
                        verbose_name="شعار",
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تلفن پشتیبانی"
                    ),
                ),
                (
                    "support_telegram",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً \u200e@username",
                        max_length=100,
                        verbose_name="تلگرام/بله پشتیبانی",
                    ),
                ),
                (
                    "sms_api_key",
                    models.CharField(
                        blank=True,
                        help_text="از پنل sms.ir، بخش برنامه\u200cنویسان ← لیست کلیدهای API",
                        max_length=200,
                        verbose_name="کلید API sms.ir",
                    ),
                ),
                (
                    "sms_otp_template_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="قالب ارسال سریع (Verify) در sms.ir",
                        null=True,
                        verbose_name="شناسه قالب کد ورود",
                    ),
                ),
                (
                    "sms_otp_param_name",
                    models.CharField(
                        default="CODE",
                        help_text="مثلاً CODE برای #CODE#",
                        max_length=50,
                        verbose_name="نام پارامتر کد در قالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
    ]
