# Generated by Django 5.2.18 on 2026-10-09 10:56

import apps.siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bale_bot_token",
            field=models.CharField(
                blank=True,
                help_text="از \u200e@botfather در بله",
                max_length=200,
                verbose_name="توکن ربات بله",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bale_bot_username",
            field=models.CharField(
                blank=True,
                help_text="بدون @، مثلاً araz_lms_bot",
                max_length=100,
                verbose_name="نام کاربری ربات بله",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bale_provider_token",
            field=models.CharField(
                blank=True,
                help_text="پول پرداخت\u200cشده در بله به این کارت/کیف پول واریز می\u200cشود",
                max_length=100,
                verbose_name="شماره کارت یا توکن کیف پول برای پرداخت بله",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bale_webhook_secret",
            field=models.CharField(
                default=apps.siteconfig.models._new_secret,
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="card_bank",
            field=models.CharField(blank=True, max_length=50, verbose_name="نام بانک"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="card_holder",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="نام صاحب کارت"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="card_number",
            field=models.CharField(
                blank=True,
                help_text="به خریدار نمایش داده می\u200cشود",
                max_length=30,
                verbose_name="شماره کارت (کارت\u200cبه\u200cکارت)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seller_address",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="آدرس فروشنده (روی فاکتور)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seller_name",
            field=models.CharField(
                blank=True,
                help_text="خالی = نام سایت",
                max_length=150,
                verbose_name="نام فروشنده (روی فاکتور)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seller_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="تلفن فروشنده (روی فاکتور)"
            ),
        ),
    ]
