# Generated by Django 5.2.18 on 2026-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0002_sitesettings_bale_bot_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="sms_paid_template_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="پارامترها: #ORDER# (شماره سفارش) و #TITLE# (نام محصول). خالی = ارسال نشود",
                null=True,
                verbose_name="قالب پیامک «پرداخت تأیید شد»",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="sms_rejected_template_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="پارامتر: #ORDER# (شماره سفارش). خالی = ارسال نشود",
                null=True,
                verbose_name="قالب پیامک «رسید تأیید نشد»",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="sms_reminder_template_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="پارامترها: #TITLE# (نام کلاس) و #TIME# (تاریخ و ساعت). خالی = ارسال نشود",
                null=True,
                verbose_name="قالب پیامک «یادآوری کلاس زنده»",
            ),
        ),
    ]
