# Generated by Django 5.2.18 on 2026-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0003_sitesettings_sms_paid_template_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="sms_answer_template_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="پارامتر: #TITLE# (نام جلسه). خالی = ارسال نشود",
                null=True,
                verbose_name="قالب پیامک «پاسخ سوال شما داده شد»",
            ),
        ),
    ]
