# Generated by Django 5.2.18 on 2026-10-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0004_sitesettings_sms_answer_template_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bale_welcome_message",
            field=models.TextField(
                blank=True,
                help_text="این پیام وقتی کاربر ربات را برای اولین بار باز می\u200cکند (بدون لینک سفارش) نشان داده می\u200cشود. خالی = پیام پیش\u200cفرض.",
                verbose_name="پیام خوش\u200cآمدگویی ربات بله",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="bale_provider_token",
            field=models.CharField(
                blank=True,
                help_text="توکن درگاه پرداخت از @BotFather در بله (منوی Bot Payments). این توکن با شماره کارت فرق دارد. اگر این فیلد خالی باشد، ربات در صورت خطا آدرس کارت\u200cبه\u200cکارت را به کاربر می\u200cدهد.",
                max_length=100,
                verbose_name="توکن درگاه پرداخت بله (provider_token)",
            ),
        ),
    ]
