# Generated by Django 5.2.18 on 2026-10-09 10:56

import apps.catalog.models
import apps.shop.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=300, verbose_name="خلاصه"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.catalog.models.cover_upload_to,
                        verbose_name="تصویر جلد",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "access_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی = برای هر دوره، مدت دسترسی خود آن دوره",
                        null=True,
                        verbose_name="مدت دسترسی (روز)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منتشر شده"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="bundles",
                        to="catalog.course",
                        verbose_name="دوره\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "پکیج",
                "verbose_name_plural": "پکیج\u200cها",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="حروف انگلیسی و عدد",
                        max_length=40,
                        unique=True,
                        verbose_name="کد",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت (تومان)")],
                        default="percent",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="درصد (۱ تا ۱۰۰) یا مبلغ به تومان",
                        verbose_name="مقدار",
                    ),
                ),
                (
                    "max_discount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="فقط برای کد درصدی؛ خالی = بدون سقف",
                        null=True,
                        verbose_name="سقف تخفیف (تومان)",
                    ),
                ),
                (
                    "min_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حداقل مبلغ خرید (تومان)"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع اعتبار"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان اعتبار"
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی = نامحدود",
                        null=True,
                        verbose_name="حداکثر تعداد استفاده",
                    ),
                ),
                (
                    "one_per_user",
                    models.BooleanField(
                        default=True, verbose_name="هر کاربر فقط یک بار"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "bundles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discount_codes",
                        to="shop.bundle",
                        verbose_name="فقط برای این پکیج\u200cها",
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="اگر هیچ دوره و پکیجی انتخاب نشود، کد برای همه معتبر است.",
                        related_name="discount_codes",
                        to="catalog.course",
                        verbose_name="فقط برای این دوره\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کدهای تخفیف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="شماره سفارش",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "discount_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تخفیف (تومان)"
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        verbose_name="مبلغ قابل پرداخت (تومان)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("review", "در انتظار تأیید رسید"),
                            ("paid", "پرداخت شده"),
                            ("rejected", "رسید تأیید نشد"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bale", "پرداخت در بله"),
                            ("card", "کارت\u200cبه\u200cکارت"),
                            ("free", "رایگان (کد تخفیف)"),
                            ("manual", "ثبت دستی ادمین"),
                        ],
                        max_length=20,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="شناسه پرداخت"
                    ),
                ),
                (
                    "receipt",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.shop.models.receipt_upload_to,
                        verbose_name="تصویر رسید",
                    ),
                ),
                (
                    "receipt_ref",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="شماره پیگیری / توضیح خریدار",
                    ),
                ),
                (
                    "receipt_submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال رسید"
                    ),
                ),
                (
                    "bale_chat_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="شناسه چت بله"
                    ),
                ),
                (
                    "admin_note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="یادداشت ادمین"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="shop.bundle",
                        verbose_name="پکیج",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="catalog.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="shop.discountcode",
                        verbose_name="کد تخفیف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("bundle__isnull", True), ("course__isnull", False)
                            ),
                            models.Q(
                                ("bundle__isnull", False), ("course__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="order_has_exactly_one_product",
                    )
                ],
            },
        ),
    ]
