# Generated by Django 5.2.18 on 2026-10-09 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_enrollment_order"),
        ("live", "0001_initial"),
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="order_has_exactly_one_product",
        ),
        migrations.AddField(
            model_name="discountcode",
            name="live_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="discount_codes",
                to="live.liveclass",
                verbose_name="فقط برای این کلاس\u200cهای زنده",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="live_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="live.liveclass",
                verbose_name="کلاس زنده",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("bundle__isnull", True),
                        ("course__isnull", False),
                        ("live_class__isnull", True),
                    ),
                    models.Q(
                        ("bundle__isnull", False),
                        ("course__isnull", True),
                        ("live_class__isnull", True),
                    ),
                    models.Q(
                        ("bundle__isnull", True),
                        ("course__isnull", True),
                        ("live_class__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="order_has_exactly_one_product",
            ),
        ),
    ]
