# Generated by Django 5.2.18 on 2026-10-09 10:22

import apps.catalog.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "دسته",
                "verbose_name_plural": "دسته\u200cها",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=300, verbose_name="خلاصه"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.catalog.models.cover_upload_to,
                        verbose_name="تصویر جلد",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "مقدماتی"),
                            ("intermediate", "متوسط"),
                            ("advanced", "پیشرفته"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="سطح",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="۰ یعنی رایگان",
                        verbose_name="قیمت (تومان)",
                    ),
                ),
                (
                    "access_days",
                    models.PositiveIntegerField(
                        blank=True,
                        default=365,
                        help_text="خالی = دائمی",
                        null=True,
                        verbose_name="مدت دسترسی (روز)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="منتشر شده"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ویرایش"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="catalog.category",
                        verbose_name="دسته",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_by",
                        to="catalog.course",
                        verbose_name="پیش\u200cنیازها",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره",
                "verbose_name_plural": "دوره\u200cها",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="catalog.course",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل",
                "verbose_name_plural": "فصل\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="شروع دسترسی"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="اگر خالی بماند، طبق «مدت دسترسی» دوره محاسبه می\u200cشود (یا دائمی).",
                        null=True,
                        verbose_name="پایان دسترسی",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "دستی (ادمین)"), ("order", "خرید")],
                        default="manual",
                        max_length=20,
                        verbose_name="منبع",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="یادداشت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="catalog.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی دوره",
                "verbose_name_plural": "دسترسی\u200cهای دوره",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video", "ویدیو"),
                            ("document", "PDF / اسلاید"),
                            ("notebook", "نوت\u200cبوک"),
                            ("geodata", "داده مکانی"),
                            ("code", "کد"),
                            ("text", "متن"),
                        ],
                        default="video",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="متن / توضیحات")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت (دقیقه)"
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, verbose_name="رایگان (پیش\u200cنمایش)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="catalog.chapter",
                        verbose_name="فصل",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه",
                "verbose_name_plural": "جلسه\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LessonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=apps.catalog.models.lesson_file_upload_to,
                        verbose_name="فایل",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="catalog.lesson",
                        verbose_name="جلسه",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل جلسه",
                "verbose_name_plural": "فایل\u200cهای جلسه",
                "ordering": ["order", "id"],
            },
        ),
    ]
